config/routes.rb
Rails.application.routes.draw do

  root to: 'gossip#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :gossip  do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

  resources :messages
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]
  resources :user , except: [:destroy]

  get '/team', to: 'user#team'
  get '/contact', to: 'user#choose_contact'
  get '/welcome/:user_entry', to: 'user#welcome'
  
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :commentable, polymorphic: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[edit update destroy]

  def new
    @comment = Comment.new
    @gossip = Gossip.find(params[:gossip_id])
    @user = User.find(@gossip.user_id)
    @users = User.full_name_list  
    @tags = TagGossip.find_tags_id(params[:gossip_id].to_i)
  end

  def edit
    @gossip = Gossip.find(params[:gossip_id])
    @usergossip = User.find(@gossip.user_id)  
    @usercomment = User.find(@comment.user_id)
    @users = User.full_name_list
    @tags = TagGossip.find_tags_id(params[:gossip_id].to_i)

  end

  def create
    @gossip = Gossip.find(params[:gossip_id])
    @user = current_user
    @users = User.full_name_list
    @tags = TagGossip.find_tags_id(params[:gossip_id].to_i)
    @comment = Comment.new(comment_params.merge(commentable: @gossip))
      if @comment.save
        # @comments = Comment.where(gossip_id: params[:gossip_id])
        redirect_to gossip_path(@gossip), notice: "Comment was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
  end

  def update
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.find(params[:id])
    @usergossip = User.find(@gossip.user_id)  
    @usercomment = User.find(@comment.user_id)
    @users = User.full_name_list
    @tags = TagGossip.find_tags_id(params[:gossip_id].to_i)
    @comment = Comment.find(params[:id])

      if @comment.update(comment_params)
        redirect_to gossip_path(@gossip), notice: "Comment was successfully updated."

      else
        render :edit, status: :unprocessable_entity
      end
  end

  def destroy
    puts @comment
    @comment.destroy
    @gossip = Gossip.find(params[:gossip_id])
    redirect_to gossip_path(@gossip), notice: "Comment was successfully destroyed."
  end

  private

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:user_id, :content)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="card m-5">
    <div class="card-header text-center">The author:   <%=link_to @usergossip.first_name, user_path(@usergossip), :class => "ml-2"%></div>
    <div class="card-body">
        <h5 class="card-title"><%=@gossip.title%>
          <%@tags.each do |tag_id|%>
            <span class="badge badge-pill" style="color:white;background-color: <%=Tag.find(tag_id).color%>;"><%=Tag.find(tag_id).title%></span>
          <%end%></h5>
        <p class="card-text"><%=@gossip.content%></p>
        <div>
            
            <h3>Edit a Comment</h3>
            <%=form_for @comment, url:gossip_comment_path(@gossip, @comment), method: :patch do |f|%>
                <%if @comment.errors.any? %>
                    <% @comment.errors.full_messages.each do |msg| %>
                        <div class="alert alert-danger"><%=msg%></div>
                    <%end%>
                <%end%>
                <p>
                <%= f.hidden_field(:user_id, {:value => current_user.id, :readonly => "readonly"}) %>
                </p>
                <p><%= f.label :content%> <br>
                <%= f.text_area(:content, {:class => "form-control"})%>
                </p>
                <p><%= f.submit({:class => "card-link btn btn-info", :value => "Update  "}) %>
                </p>
                <%end%>
                <div class="card-text text-center">
                <%=link_to "Cancel", gossip_path(@gossip), :class => "btn btn-light mb-3 text-center ml-5"%>
                <%=link_to "Delete", gossip_comment_path(@gossip, @comment) , :method => :delete, :class => "btn btn-outline-danger mb-3 text-center ml-5"%>
                </div>
        </div>
        <div class="card-footer bg-transparent border-success text-center">
        posted: <%=@gossip.created_at%>
        </div>
  </div>
</div>
<div class="container text-center">
<%=link_to "Back to Gossips", gossip_index_path, :class => "card-link btn btn-light" %>
</div>
    

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<div class="card m-5">
    <div class="card-header text-center">The author:   <%=link_to @user.first_name, user_path(@user), :class => "ml-2"%></div>
    <div class="card-body">
        <h5 class="card-title"><%=@gossip.title%>
          <%@tags.each do |tag_id|%>
            <span class="badge badge-pill" style="background-color: <%=Tag.find(tag_id).color%>;"><%=Tag.find(tag_id).title%></span>
          <%end%></h5>
        <p class="card-text"><%=@gossip.content%></p>
        <div>
            <%=link_to "Cancel", gossip_path(@gossip), :class => "btn btn-light mb-3 text-center ml-5"%>
        

            <h3>Add a Comment</h3>
            <%=form_for @comment, url:gossip_comments_path do |f|%>
                <%if @comment.errors.any? %>
                    <% @comment.errors.full_messages.each do |msg| %>
                        <div class="alert alert-danger"><%=msg%></div>
                    <%end%>
                <%end%>
                <p> <%= f.label :user_id%> <br> 
                <%= f.select(:user_id, options_for_select(@users, :selected => params[:user_id])) %>
                </p>
                <p><%= f.label :content%> <br>
                <%= f.text_area(:content, {:class => "form-control"})%>
                </p>
                <p><%= f.submit({:class => "card-link btn btn-info"}) %>
                </p>
                <%end%>
        </div>
        <div class="card-footer bg-transparent border-success text-center">
        posted: <%=@gossip.created_at%>
        </div>
  </div>
</div>
<div class="container m-5 text-center">
<%=link_to "Back to Gossips", gossip_index_path, :class => "card-link btn btn-light" %>
</div>
    

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>