config/routes.rb
Rails.application.routes.draw do

  root to: 'gossip#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :gossip  do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

  resources :messages
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]
  resources :user , except: [:destroy]

  get '/team', to: 'user#team'
  get '/contact', to: 'user#choose_contact'
  get '/welcome/:user_entry', to: 'user#welcome'
  
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    has_many :comments, as: :commentable
    has_many :tag_gossips, :dependent => :destroy
    has_many :tags, through: :tag_gossips
    has_many :likes
    belongs_to :user
    validates :title, presence: true
    validates :content, presence: true

def self.search(search)
    if search #le champ est rempli
        result = Gossip.where(['lower(content) LIKE ? or lower(title) LIKE ?', "%#{search.downcase}%", "%#{search.downcase}%"])
        if result
            @gossips = result
        else
            @gossips = Gossip.all
        end
    else #le champ est vide
        @gossips = Gossip.all
    end
end

def self.search_by_city(city_name)
    list=[]
    city = City.find_by(name: city_name)
    puts city
    if city #la recherche aboutit
        users = User.where(city: city)
        puts users
        users.each do |user|
             list.concat(Gossip.where(user: user))
        end
        list
    else #le champ est vide
        @gossips = Gossip.all
    end
end

def self.get_gossip_list(users)
    list = []
    users.each do |user|
        list.concat(Gossip.where(user: user))
    end
    list
end

def count_likes
    self.likes.count
end

def is_liked?(user)
    Like.find_by(user: user, gossip_id: self.id)!= nil
end

def get_like(user)
    Like.find_by(user: user, gossip_id: self.id)
end

end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
    before_action :set_gossip, only:[ :show, :edit, :update, :destroy]
    before_action :authenticate_user, only: [:new, :create]
    before_action :authenticate_current_user, only: [:edit, :update, :destroy]

    def index
        @gossips = Gossip.search(params[:search]).order(:id)
        puts current_user
    end

    def search
        @gossips = Gossip.all.order(:id)
    end

    def show
        @comments = @gossip.comments
        @users = User.full_name_list
        @user = User.find(@gossip.user_id)
        @tags = TagGossip.find_tags(@gossip)
        @comment = Comment.new
        @city = City.find(@user.city_id)
        if @gossip.is_liked?(@user)
            @like = @gossip.get_like(@user)
        end
    end

    def new
        puts params
        @users = User.full_name_list
        @gossip = Gossip.new
        @tags = Tag.all
    end

    def create
        puts params
        @tags = Tag.all
        @gossip = Gossip.new(gossip_params)
                if @gossip.save
                    tags = params[:tags].split
                    if tags
                        tags.each do |tag|
                            TagGossip.create!(tag_id: Tag.get_id(tag), gossip_id: @gossip.id)
                        end
                    end
                    flash[:success] = "Gossip Created"
                    redirect_to gossip_index_path
                else
                    render :new
                end
    end

    def edit
        @user = User.find(@gossip.user_id)
        @tags_list = Tag.get_list(@gossip)
        @tags = Tag.all
    end

    def update
        if @gossip.update(gossip_params)
            tags = params[:tags].split
                    if tags #si params non vide
                        TagGossip.where("gossip_id = ?", @gossip.id).delete_all
                        tags.each do |tag| #nom du tag
                            tg = TagGossip.new(tag_id: Tag.get_id(tag), gossip: @gossip)
                            if tg.save
                            end
                        end
                    end
            flash[:success] = "Gossip Updated"
            redirect_to @gossip
        else
            render :edit
        end
    end

    def destroy
        @gossip.destroy
        flash[:warning] = "Gossip deleted"
        redirect_to gossip_index_path
    end

    def search
        @gossips = Gossip.search(params[:search])
    end

    private 
    
    def set_gossip
        @gossip = Gossip.find(params[:id])
    end 

    def gossip_params
        params.require(:gossip).permit(:title, :content, :user_id)
    end

    def authenticate_user
        unless logged_in?
          flash[:warning] = "You should log in to gossip!"
          redirect_to new_session_path
        end
    end

    def authenticate_current_user
        unless current_user == @gossip.user
          flash[:warning] = "You are not authorized to modify/delete this gossip!"
          redirect_to gossip_index_path
        end
    end

end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/views/gossip/edit.html.erb
<h1>Update Gossip</h1>

<%=form_for @gossip, url: gossip_path(@gossip), method: :patch do |f|%>
    <%if @gossip.errors.any? %>
        <% @gossip.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%=msg%></div>
    <%end%>
<%end%>
<p>
 <%= f.hidden_field(:user_id, :readonly => "readonly") %>
</p>
<p>
<%= f.label :title%> <br> 
<%= f.text_field(:title, {:class => "form-control"})%>
</p>
<p>
<%= f.label :content%> <br>
<%= f.text_area(:content, {:class => "form-control"})%>
</p>
<p>
<br>
<%= label_tag :tags%>
<%@tags.each do |tag|%>
    <%= label_tag tag.id, "#{tag.title}" %>
    <%= check_box_tag 'tags_id[]', tag.id%>
<%end%>
<%= text_field_tag :tags, @tags_list%>
</p>
<p>
<%= f.submit({:value => "Update", :class => "card-link btn btn-info"}) %>
<%=link_to "Cancel", gossip_path(@gossip), :class => "card-link btn btn-light"%>
</p>
<%end%>


<div class="container m-5 text-center">
<%=link_to "Back to Gossips", gossip_index_path, :class => "card-link btn btn-light" %>
</div>
    

app/views/gossip/index.html.erb
    <div class="text-center"><h1>Welcome!</h1></div>


    <div class="text-center">
    <p>Si tu as du croustillant à nous partager, tu peux :</p>
    <%=link_to "Create a new gossip", new_gossip_path, :class => "card-link btn btn-info" %><br><br>
    </div>
    <h3>Tous les potins THP! </h3>
    <div class="flex-container">
        <% @gossips.each_with_index.map do |gossip, index| %>
            <div class="card m-4 card-container">
                <div class="card-index card-header space-around">
                    <span style="font-family:'Macondo';font-size:1.5rem;"><%=link_to "N°#{index + 1}", gossip_path(gossip) %>&nbsp;&nbsp;<%="by #{User.find(gossip.user_id).first_name}"%></span>
                     <%if logged_in?%>
                        <%if gossip.is_liked?(current_user)%>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <%=button_to gossip_like_path(gossip.id, gossip.get_like(current_user).id), method: :delete, :class => "btn btn-primary liked float-end" do %>
                                <span><i class="bi bi-heart-fill"></i></span> <% end %>
                        <%else%>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <%=button_to gossip_likes_path(gossip.id), :class => "btn btn-outline-primary disliked float-end" do %>
                                <span><i class="bi bi-heart"></i></span> <%end%>
                        <%end%>
                    <%end%>
                </div>
                <div class="card-body">
                    <p><h5><%=link_to gossip.title, gossip_path(gossip) %></h5></p>
                    <%=gossip.likes.count%> <i class="bi bi-suit-heart-fill"></i>&nbsp;&nbsp;<%=gossip.comments.count%>&nbsp;<i class="bi bi-chat-left-text-fill"></i><br>
                </div>
                <div class="card-bottom">
                    <%TagGossip.find_tags_id(gossip.id).each do |tag_id|%>
                        <span class="tag badge badge-pill m-2" style="color:white;background-color: <%=Tag.find(tag_id).color%>;"><%=Tag.find(tag_id).title%></span>
                    <%end%>
                </div>
            </div>
        <% end %>
    </div>
 

app/views/gossip/new.html.erb
<h1>Create Gossip</h1>

<%=form_for :gossip, url: gossip_index_path do |f|%>
    <%if @gossip.errors.any? %>
        <% @gossip.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%=msg%></div>
        <%end%>
    <%end%>
<p> <br> 
 <%= f.hidden_field(:user_id, {:value => current_user.id, :readonly => "readonly"}) %>
</p>
<p>
<%= f.label :title%> <br> 
<%= f.text_field(:title, {:class => "form-control"})%>
</p>
<p>
<%= f.label :content%> <br>
<%= f.text_area(:content, {:class => "form-control"})%>
</p>

<%= label_tag :tags%> <br> 

<%@tags.each do |tag|%>
<%= label_tag tag.id, "#{tag.title}" %>
<%= check_box_tag 'tags_id[]', tag.id%>
<%end%>

<%= text_field_tag(:tags)%>
<p>
<br><%= f.submit({:class => "card-link btn btn-light"}) %>
<%=link_to "Cancel", gossip_index_path, :class => "card-link btn btn-light"%>
</p>
<%end%>

app/views/gossip/show.html.erb
<div class="containergit  text-center">
<%=link_to "Back to Gossips", gossip_index_path, :class => "card-link btn btn-light" %>
</div>

<div class="card m-5">
    <div class="card-header d-flex space-around text-center ">
    <span style="font-family:'Macondo';font-size:1.5rem;">The author:  &nbsp;  <%=link_to @user.first_name, user_path(@user), :class => "me-5"%>
    From: &nbsp; <%=link_to @city.name, city_path(@city), :class => "me-5"%> </span>
    </div>
    <div class="card-body">
        <h3 class="card-title"><%=@gossip.title%></h3>
          <%@tags.each do |tag|%>
            <span class="badge badge-pill" style="color:white;background-color: <%=tag.color%>;"><%=tag.title%></span>
          <%end%>
        <br><p class="card-text mt-3"><%=@gossip.content%></p>
              <div class="text-center">
            <%if current_user == @gossip.user%>
              <%=link_to "Edit", edit_gossip_path(@gossip), :class => "btn btn-info mb-3 text-center ml-5"%>
              <%=link_to "Delete", @gossip, :method => :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-outline-danger mb-3 text-center" %>
             <%end%> 
          <%if logged_in?%>
            <%if@gossip.is_liked?(current_user)%>
                <%=button_to gossip_like_path(@gossip.id, @gossip.get_like(current_user).id), method: :delete, :class => "btn btn-primary liked" do %>
                  <span><i class="bi bi-heart-fill"></i></span> <% end %>
            <%else%>
                <%=button_to gossip_likes_path(@gossip.id), :class => "btn btn-outline-primary disliked" do %>
                  <span><i class="bi bi-heart"></i></span> <%end%>
            <%end%>
          <%end%>
          <span><%=@gossip.count_likes%> Likes</span>
              
              </div>
        
        <div class="m-4">
          <h4>Comments</h4>
          <ul class="list-group">
            <% @comments.each do |comment| %>
              <li class="list-group-item">
              <tr>
              <td><strong><%= User.find(comment.user_id).full_name%> :</strong></td>
              <td><%= comment.content %></td>
              <%if current_user == comment.user %> 
              <%=link_to "Edit", edit_gossip_comment_path(@gossip, comment), :class => "badge badge-info mb-3 text-center", :style => "background-color:cyan"%>
              <%=link_to "Comment", edit_gossip_comment_path(@gossip, comment), :class => "badge badge-info mb-3 text-center", :style => "background-color:cyan"%>
              <%end%><br>
              </tr>
              </li>
            <% end %>
          
          </ul>
        </div>
        <%if logged_in?%>
          <div class="m-4">
            <h5>Add a Comment</h5>
            <%=form_for @comment, url:gossip_comments_path(@gossip, @comment) do |f|%>
                <%if @comment.errors.any? %>
                    <% @comment.errors.full_messages.each do |msg| %>
                        <div class="alert alert-danger"><%=msg%></div>
                    <%end%>
                <%end%>
                <p>
                <%= f.hidden_field(:user_id, {:value => current_user.id, :readonly => "readonly"}) %>
                </p>
                <p><%= f.label :content%> <br>
                <%= f.text_area(:content, {:class => "form-control"})%>
                </p>
                <p><%= f.submit({:class => "card-link btn btn-info"}) %>
                </p>
              <%end%>
            </div>
        <%end%>
          <div class="card-footer bg-transparent border-success text-center">
        posted: <%=@gossip.created_at%>
        </div>
  </div>
</div>
<div class="container-fluid text-center">
<%=link_to "Back to Gossips", gossip_index_path, :class => "card-link btn btn-light" %>
</div>
    