config/routes.rb
Rails.application.routes.draw do

  root to: 'gossip#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :gossip  do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

  resources :messages
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]
  resources :user , except: [:destroy]

  get '/team', to: 'user#team'
  get '/contact', to: 'user#choose_contact'
  get '/welcome/:user_entry', to: 'user#welcome'
  
end

app/models/user.rb
class User < ApplicationRecord
    has_many :gossips, dependent: :destroy
    belongs_to :city
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
    has_many :comments, as: :commentable
    validates :password, presence: true, length: { minimum: 6 }
    validates :age, numericality: { only_integer: true }
    validates :email, 
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

    has_secure_password

    def self.full_name_list
        list =[]
        User.all.each do |user|
            list << [(user.first_name + " "+user.last_name), user.id]
        end
        list
    end

    def full_name
        (self.first_name + " "+self.last_name)
    end

    def remember(remember_token)
        remember_digest = BCrypt::Password.create(remember_token)
        self.update_attribute(:remember_digest, remember_digest)
        puts "remember_digest updated!"
    end
    

end

app/controllers/user_controller.rb
class UserController < ApplicationController

def index
    @users = User.all
end

def show
    @user = User.find(params[:id])
    @gossips = Gossip.where(user: @user)
end

def new
    @cities = City.name_list
    @user = User.new
    @remember = false
end

def create
    puts params
    @cities = City.name_list
    @user = User.new(user_params)
    if @user.save
        log_in(@user)
        remember(@user) if remember_user?
        redirect_to gossip_index_path
    else
        flash[:alert]= "User not saved"
        render :new
    end
end

def contact
    @contact = User.find(params[:id])
end

def choose_contact
    @users = User.all
end

private

def user_params
    params.require(:user).permit(:first_name, :last_name, :city_id, :age, :email, :description, :password, :password_confirmation)
end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/choose_contact.html.erb
<div class="row">

<div class="col photo">
    <img src="https://images.pexels.com/photos/2346006/pexels-photo-2346006.jpeg?auto=format%2Ccompress&cs=tinysrgb&dpr=1&w=500">
    <div class="photos">Photos</div>
</div>

<div class="col text-center">
    <h2> Send us a message </h2><br><br><br>
    <p>gossip_thp@closer.org</p>
    <%=link_to "Message", new_message_path, :class => "btn btn-outline-primary ms-1"%>
</div>

</div>

app/views/user/index.html.erb
<div class="row">
    <%@users.each do |user|%>
    <div class="col-lg-4">
        <div class="card mb-4">
            <div class="card-body text-center" style="background-color:#<%="%06x" % (rand * 0xffffff)%>";>
                <img src="https://source.unsplash.com/200x200/?portrait?sig=<%=rand(1..150)%>" 
                alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">
                <h5 class="my-3">
                <%=link_to user.first_name, user_path(user), :style => "color:black;"%></h5>
                <div class="d-flex justify-content-center"> 
                    <%=link_to "Message", new_message_path, :class => "btn btn-outline-primary ms-1"%>
                </div>
            </div>
        </div> 
    </div>
    <div class="col-lg-8">
        <div class="card mb-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-3">
                        <p>Full Name</p>
                    </div>
                    <div class="col-sm-9">
                        <p><%=user.full_name %></p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <p>Email</p>
                    </div>
                    <div class="col-sm-3">
                        <p><%=user.email%></p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <p>Age</p>
                    </div>
                    <div class="col-sm-3">
                        <p><%=user.age%></p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <p>City</p>
                    </div>
                    <div class="col-sm-3">
                        <p><%=user.city.name%></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <%end%>
</div>

app/views/user/new.html.erb
<div class="m-5">

<h2>Sign up</h2>

<%=form_for :user, url: user_index_path do |f|%>
    <%if @user.errors.any? %>
        <% @user.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%=msg%></div>
        <%end%>
    <%end%><br>

<%# <p><%= f.label :city_id%>
<%# <%= f.select(:city_id, options_for_select(@cities, :selected => params[:city_id])) %>

<%# <%= f.select :, options_for_select([["Select One", ""], "Cell", "Work", "Office", "Home", "Other"]), :class => 'genForm_dropBox' %> 

<p><%= f.label :city_id%> 
<%= f.text_field(:city_id, {:class => "form-control"})%></p>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Don't know your city id?
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Cities available</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <%@cities.each do |city|%>
        <tr>
            <td><%=city[1]%></td>
            <td><%=city[0]%></td><br><br>
        </tr>
        <%end%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<br>
<br>

<p><%= f.label :first_name%> <br> 
<%= f.text_field(:first_name, {:class => "form-control"})%>
<%= f.label :last_name%> <br> 
<%= f.text_field(:last_name, {:class => "form-control"})%></p>
<p><%= f.label :email%> <br> 
<%= f.text_field(:email, {:class => "form-control"})%>
<%= f.label :password%> <br>
<%= f.text_field(:password, {:class => "form-control", :type => "password"})%>
<%= f.label :password_confirmation%><br>
<%= f.text_field(:password_confirmation, {:class => "form-control", :type => "password"})%></p>
<p><%= f.label :age%> <br> 
<%= f.text_field(:age, {:class => "form-control"})%></p>
<p><%= f.label :description%> <br> 
<%= f.text_area(:description, {:rows => 8, :cols => 40, :class => "form-control"})%></p>
<br>

<%= f.submit 'Sign up', :class => 'card-link btn btn-info' %>
<%= f.submit 'Sign up and Remember me', :class => 'card-link btn btn-info' %>

<% end %>
<br>



</div>

app/views/user/show.html.erb
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-6 mb-4 mb-lg-0" style="width:100%;">
        <div class="card mb-3" style="border-radius: .5rem;">
          <div class="row g-0">
            <div class="col-md-4 gradient-custom text-center text-white"
              style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp"
                alt="Avatar" class="img-fluid my-5" style="width: 80px;" />
              <h5><%=@user.full_name%></h5>
              <p><%=@user.city.name%></p>
              <i class="far fa-edit mb-5"></i>
              <%=link_to "Message", new_message_path, :class => "btn btn-outline-primary ms-1"%>
            </div>
            <div class="col-md-8">
              <div class="card-body p-4">
                <h6>Description</h6>
                <hr class="mt-0 mb-4">
                <div class="row pt-1 m-4">
                  <%=@user.description%>
                </div>
                <h6>Gossips</h6>
                <hr class="mt-0 mb-4">
                <div class="row pt-1">
                  <div class="col-6 mb-3">
                    <h6>Title</h6>
                    <%@gossips.each do |gossip|%>
                    <p class="text-muted"><%=link_to gossip.title, gossip_path(gossip)%></p>
                    <%end%>
                  </div>
                  <div class="col-6 mb-3">
                    <h6>Posted</h6>
                    <%@gossips.each do |gossip|%>
                    <p class="text-muted"><%=gossip.created_at%></p>
                    <%end%>
                  </div>
                </div>
                
                <div class="d-flex justify-content-start">
                  <a href="#!"><i class="fab fa-facebook-f fa-lg me-3"></i></a>
                  <a href="#!"><i class="fab fa-twitter fa-lg me-3"></i></a>
                  <a href="#!"><i class="fab fa-instagram fa-lg"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/user/team.html.erb
<section>
  <div class="row d-flex justify-content-center">
    <div class="col-md-10 col-xl-8 text-center">
      <h3 class="mb-4">Team</h3>
      <p class="mb-4 pb-2 mb-md-5 pb-md-0">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit, error amet
        numquam iure provident voluptate esse quasi, veritatis totam voluptas nostrum
        quisquam eum porro a pariatur veniam.
      </p>
    </div>
  </div>

  <div class="row text-center">
    <div class="col-md-4 mb-5 mb-md-0">
      <div class="card testimonial-card">
        <div class="card-up" style="background-color: #9d789b;"></div>
        <div class="avatar mx-auto bg-white">
          <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(1).webp"
            class="rounded-circle img-fluid" />
        </div>
        <div class="card-body">
          <h4 class="mb-4">Hortense Du Plessis</h4>
          <hr />
          <p class="dark-grey-text mt-4">
            <i class="fas fa-quote-left pe-2"></i>Je suis devenue une amazing meuf BCBG avec THP, j'ai échangé les dreads et le sarouel pour la jupe plissée, allez viens à THP!
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-4 mb-5 mb-md-0">
      <div class="card testimonial-card">
        <div class="card-up" style="background-color: #7a81a8;"></div>
        <div class="avatar mx-auto bg-white">
          <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(2).webp"
            class="rounded-circle img-fluid" />
        </div>
        <div class="card-body">
          <h4 class="mb-4">Lisa Cudrow</h4>
          <hr />
          <p class="dark-grey-text mt-4">
            <i class="fas fa-quote-left pe-2"></i>De Montpellier, si je ne suis pas derrière mon écran je suis à la plage pour cramer mes neurones, on n'a qu'une vie!
        </div>
      </div>
    </div>
    <div class="col-md-4 mb-0">
      <div class="card testimonial-card">
        <div class="card-up" style="background-color: #6d5b98;"></div>
        <div class="avatar mx-auto bg-white">
          <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(9).webp"
            class="rounded-circle img-fluid" />
        </div>
        <div class="card-body">
          <h4 class="mb-4">Giovanni Della Scala</h4>
          <hr />
          <p class="dark-grey-text mt-4">
            <i class="fas fa-quote-left pe-2"></i>Comme tout beau gosse de Paris, je suis adepte de Tinder
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/user/welcome.html.erb
BIENVENUE <%=params[:user_entry]%> ! Ici c'est notre super site de gossips, il est chouette, non ?