config/routes.rb
Rails.application.routes.draw do

  root to: 'gossip#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :gossip  do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

  resources :messages
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]
  resources :user , except: [:destroy]

  get '/team', to: 'user#team'
  get '/contact', to: 'user#choose_contact'
  get '/welcome/:user_entry', to: 'user#welcome'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
    has_many :comments, as: :commentable
    validates :name, presence: true

def self.name_list
    list =[]
        City.all.each do |citi|
            list << [citi.name , citi.id]
        end
    list
end

end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :commentable, polymorphic: true

end

app/models/gossip.rb
class Gossip < ApplicationRecord
    has_many :comments, as: :commentable
    has_many :tag_gossips, :dependent => :destroy
    has_many :tags, through: :tag_gossips
    has_many :likes
    belongs_to :user
    validates :title, presence: true
    validates :content, presence: true

def self.search(search)
    if search #le champ est rempli
        result = Gossip.where(['lower(content) LIKE ? or lower(title) LIKE ?', "%#{search.downcase}%", "%#{search.downcase}%"])
        if result
            @gossips = result
        else
            @gossips = Gossip.all
        end
    else #le champ est vide
        @gossips = Gossip.all
    end
end

def self.search_by_city(city_name)
    list=[]
    city = City.find_by(name: city_name)
    puts city
    if city #la recherche aboutit
        users = User.where(city: city)
        puts users
        users.each do |user|
             list.concat(Gossip.where(user: user))
        end
        list
    else #le champ est vide
        @gossips = Gossip.all
    end
end

def self.get_gossip_list(users)
    list = []
    users.each do |user|
        list.concat(Gossip.where(user: user))
    end
    list
end

def count_likes
    self.likes.count
end

def is_liked?(user)
    Like.find_by(user: user, gossip_id: self.id)!= nil
end

def get_like(user)
    Like.find_by(user: user, gossip_id: self.id)
end

end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
    validates :user, uniqueness: { scope: :gossip }
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord

    belongs_to :sender, class_name: "User"
    has_many :recipients, class_name: "User"
    validates :content, presence: true
    
    validate :recipient_is_not_sender

    def recipient_is_not_sender
        if :sender == :recipient
            errors.add(:recipient, "The recipient cannot be the sender")
        end
    end
    
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tag_gossips, :dependent => :destroy
    has_many :gossips, through: :tags_gossips

def self.get_id(name)
    tag = Tag.where('title LIKE ?', "%#{name}%")
    if tag.exists?
        tag.first.id
    else
        color = "#" + "%06x" % (rand * 0xffffff)
        tag = Tag.create(title: "#".concat(name), color: color)
        tag.id
    end
end

def self.get_list(gossip)
    list = TagGossip.find_tags_id(gossip)
    list.map!{ |id| Tag.find(id).title[1..-1]}
    list.join(" ")
end


end

app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
    belongs_to :tag
  belongs_to :gossip
  validates :tag_id, uniqueness: { scope: :gossip_id }

  def self.find_tags_id(gossip)
    TagGossip.where(gossip: gossip).pluck(:tag_id)
  end

  def self.find_tags(gossip)
    list = []
    tags_ids = TagGossip.find_tags_id(gossip)
    tags_ids.each do |tag_id|
      list << Tag.find(tag_id)
    end
    list
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :gossips, dependent: :destroy
    belongs_to :city
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
    has_many :comments, as: :commentable
    validates :password, presence: true, length: { minimum: 6 }
    validates :age, numericality: { only_integer: true }
    validates :email, 
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

    has_secure_password

    def self.full_name_list
        list =[]
        User.all.each do |user|
            list << [(user.first_name + " "+user.last_name), user.id]
        end
        list
    end

    def full_name
        (self.first_name + " "+self.last_name)
    end

    def remember(remember_token)
        remember_digest = BCrypt::Password.create(remember_token)
        self.update_attribute(:remember_digest, remember_digest)
        puts "remember_digest updated!"
    end
    

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_gossip, only: %i[create, destroy]



  def create
    puts params
    @gossip = Gossip.find(params[:gossip_id])
    like = Like.create!(gossip: @gossip, user: current_user)
    if like.save
      redirect_back(fallback_location: root_path)
      # redirect_to gossip_path(@gossip)
    else
      redirect_to root_path
    end
 
  end

  def destroy
    @gossip = Gossip.find(params[:gossip_id])
    @gossip.get_like(current_user).destroy
    redirect_back(fallback_location: root_path)
  end

  def set_gossip
    @gossip = Gossip.find(params[:gossip_id])
  end

  private
  def redirect_to_default
    redirect_to root_path
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

def index
    @users = User.all
end

def show
    @user = User.find(params[:id])
    @gossips = Gossip.where(user: @user)
end

def new
    @cities = City.name_list
    @user = User.new
    @remember = false
end

def create
    puts params
    @cities = City.name_list
    @user = User.new(user_params)
    if @user.save
        log_in(@user)
        remember(@user) if remember_user?
        redirect_to gossip_index_path
    else
        flash[:alert]= "User not saved"
        render :new
    end
end

def contact
    @contact = User.find(params[:id])
end

def choose_contact
    @users = User.all
end

private

def user_params
    params.require(:user).permit(:first_name, :last_name, :city_id, :age, :email, :description, :password, :password_confirmation)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/likes_helper.rb
module LikesHelper

end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def current_user
        if session[:user_id]
            User.find(session[:user_id])
        elsif cookies[:user_id]
            puts "on regarde si on a pas déjà un cookie"
            user = User.find_by(id: cookies[:user_id])
            if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
                log_in(user)
                user
            end
        end
    end
    
    def log_in(user)
        session[:user_id] = user.id
        puts"log in passed"
    end

    def logged_in?
        session[:user_id]!=nil
    end

    def remember(user)
        # ici je vais créer un remember_token qui est une suite aléatoire de caractères
        remember_token = SecureRandom.urlsafe_base64
        puts "remember_token : #{remember_token}"
        # j'ai mon token, je vais stocker son digest en base de données :    
        user.remember(remember_token)
        puts "fonction user.remember passed!"
        #  maintenant, je vais créer les cookies : un cookie qui va conserver l'user_id, et un autre qui va enregistrer le remember_token
        cookies.permanent[:user_id] = user.id
        cookies.permanent[:remember_token] = remember_token
    end

    def forget(user)
        user.update_attribute(:remember_digest, nil)
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    def log_out(user)
        forget(user)
        session.delete(:user_id)
    end

    def remember_user?
        params[:commit] == "Log in and Remember me" || params[:commit] == "Sign up and Remember me"
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Macondo&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    

  </head>

  <body>

<nav class="navbar navbar-expand-lg navbar-light bg-light" style="z-index:11035;">
  <div class="container-fluid">
    <%=link_to "The Gossip Project", root_path, :class => "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" >
        <li class="nav-item">
          <%=link_to "Home", root_path, :class => "nav-item nav-link active" %></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Community
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li class="nav-item"><%=link_to "Gossipers", user_index_path, :class => "dropdown-item" %></li><br>
            <li class="nav-item"><%=link_to "Team", team_path, :class => "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li class="nav-item"><%=link_to "Contact", contact_path, :class => "dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item">
        <%=link_to "Cities", cities_path, :class => "nav-item nav-link" %>
        </li>
        
        <li><%=logged_in?%></li>
        <%if logged_in?%>
        <div class="dropdown">
          <button class="btn btn-info dropdown-toggle mx-5" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
              Log Out </button>
          <ul class="dropdown-menu text-center" aria-labelledby="dropdownMenuButton1">
            <li><div class="text-center">&nbsp;&nbsp;<%="Logged as #{current_user.full_name}"%></div></li>
            <li><%=link_to "Log Out", session_path(session.id), :method => "delete", :class => "dropdown-item btn btn-light"  %></li>
          </ul>
        </div>
        <%else%>
        <div class="dropdown">
          <button class="btn btn-info dropdown-toggle mx-5" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
              Log In </button>
          <ul class="dropdown-menu text-center" aria-labelledby="dropdownMenuButton1">
            <li><%=link_to "Sign In", new_session_path, :class => "dropdown-item btn btn-light" %></li>
            <li><%=link_to "Sign Up", new_user_path, :class => "dropdown-item btn btn-light" %></li>
          </ul>
        </div>
        <%end%>
      </ul>
      <div style= "display:inline;">
      <ul class="navbar-nav text center">
        <%= form_tag(gossip_index_path, :method => "get", :item_wrapper_class => 'inline') do %>
          <li class="nav-item"><%= text_field_tag 'search', params[:search], class: "form-control mb-1", placeholder: "Search" %></li>
          <li class="nav-item text-center"><%= submit_tag "Search" %></li>
        <% end %>
      </ul>
      </div>

      <%# <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> %>

    </div>
  </div>
</nav>

  <div class="p-3 container">
    <% flash.each do |type, msg| %>
    <div class=" alert alert-<%= type %> alert-dismissable fade show" role="alert">
    <button type="button" class="btn-close right" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= msg %></div>
    <% end %>
    
    <%= yield %>
  </div>

  </body>
</html>